### ISSUE TITLE
prisma optimize login docker

### ISSUE THREAD

**Issue by yovanoc** [prisma/optimize-feedback#3]
## Problem

Impossible to optimize login in docker

## Suggested solution

`npx prisma@optimize platform auth login --early-access --optimize --token TOKEN`

token taken from the UI

or

`npx prisma@optimize platform auth login --early-access --optimize --login LOGIN --password PASS`

or

`npx prisma@optimize platform auth login --early-access --optimize --redirect-uri DOCKER_HOST`

but annoying to do manual action during docker build

EDIT: could be other 'prod' things than docker too, like Vercel or other if we want this under a certain flag

**Comment by jasonmacdonald** [comment]
Can confirm from within Docker the login does not work. I get the following error.

```
❯ npx prisma@optimize platform auth login --early-access --optimize

Authenticating to Prisma Platform CLI via browser.

Visit the following URL in your browser to authenticate:
https://console.prisma.io/auth/optimize?state=<snipped>&source=cli
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [
    'https://console.prisma.io/auth/optimize?state=<snipped>&source=cli'
  ]
}
```
Not much to go on.

Going to the URL forwards to http://127.0.0.1:34047/?token=<Token>, which results in a 404, presumably because the local service never started due to the error.

**Comment by millsp** [comment]
Hey, thanks for the report. We have released Prisma Optimize in GA, version 1, and this is no longer an issue thanks to API tokens. Get started with the new Optimize experience over here https://www.prisma.io/data-platform/optimize.
