### ISSUE TITLE
Offline support for viewing query reports

### ISSUE THREAD

**Issue by spenweb** [prisma/optimize-feedback#8]
I would like to have an option to view the query reports offline/locally and without having to sign in. 

Side note: There was no GitHub issue template for providing feedback so I thought the closest template was the "Bug report". Please let me know if there is a better place to add this and how I could contribute to such a feature!

**Comment by millsp** [comment]
Hey @spenweb, unfortunately this is currently a non-goal as Prisma Optimize is part of our Data Platform. I am thus closing this issue, but we appreciate your feedback. By the way, we have release Prisma Optimize into GA with new features and improvement, you can check it out over here https://github.com/prisma/optimize-feedback.
